
package com.pe.apps.ws;

import javax.xml.ws.WebFault;

import com.pe.apps.schema.EmployeeException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebFault(name = "employeeExceptionElement", targetNamespace = "http://com.pe.apps/schema")
public class EmployeeExceptionMessage extends Exception {

   /**
     * Esta clase fue generada por JAX-WS RI.
     * JAX-WS RI 2.2.11-b150616.1732
     * Versión fuente generada: 2.2
     *
   */
    private EmployeeException faultInfo;

    /**
     *
     * @param faultInfo
     * @param message
     */
    public EmployeeExceptionMessage(String message, EmployeeException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     *
     * @param faultInfo
     * @param cause
     * @param message
     */
    public EmployeeExceptionMessage(String message, EmployeeException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
      *
      * @devolver
      * devuelve el bean de error: com.pe.apps.schema.EmployeeException
    */
    public EmployeeException getFaultInfo() {
        return faultInfo;
    }

}
